author           = InnovAnon
depends          = 3d_armor,beds,default,drinks,doors,edit_skin,fakelib,ia_gender,ia_util,name_generator,player_monoids,star
description      = Minetest fake userdata library
name             = ia_fake_player
optional_depends = sleeping_mat
title            = IA Fake Player

