author           = InnovAnon
depends          = default,ia_util
description      = Minetest fake userdata library
name             = ia_fake_player
optional_depends =
title            = IA Fake Player

