author           = InnovAnon
depends          = default,3d_armor,edit_skin,fakelib,ia_gender,ia_util,name_generator,player_monoids
description      = Minetest fake userdata library
name             = ia_fake_player
optional_depends =
title            = IA Fake Player

